
//% color="#0082FC" icon="\uf293" block="PKS Driver"
namespace pksdriver {

    // it is not a good idea to use global variables but i dont care
    let connected = false;
    
    // parent -> [child1, child2, ...]
    let parentChildrenMap: { [parent: string]: string[] } = {};
    
    // parent.child -> value
    let statesMap: { [compositeKey: string]: string } = {};
    
    // parent -> component type (e.g., "B", "S", "TF", "J", "O")
    let componentTypesMap: { [componentName: string]: string } = {};
    
    // update the maps when the app sends data to microbit
    let updateMaps = (name: string, value: string): void => {
        let parentName = "";
        let actualChildName = "";
        let isFound = false;

        // Find the parent of the child (if exists)
        
        // Case A: 1 attribute components
        if (parentChildrenMap[name] && parentChildrenMap[name][0] === "value") {
            parentName = name;
            actualChildName = "value";
            isFound = true;
        } else {
            // Case B: Nested child (e.g., 'angle1' inside 'Joystick')
            let keys = Object.keys(parentChildrenMap);
            for (let i = 0; i < keys.length; i++) {
                let p = keys[i];
                if (parentChildrenMap[p].indexOf(name) !== -1) {
                    parentName = p;
                    actualChildName = name;
                    isFound = true;
                    break;
                }
            }
        }

        // Notes on value
        // Button/ToggleButton: [value]. 0 or 1
        // Slider: [value]. number belonging to [min, max]
        // TextField: [value]. value: string
        // Joystick: [angleName, strengthName]. angle: number, strength: number
        // Variable: [value]. value: number (any).

        // Derive key and update values
        let compositeKey = "";
        if (isFound) {
            compositeKey = parentName + "." + actualChildName;
        }

        if (isFound && compositeKey !== "") {
            statesMap[compositeKey] = value;
        } else {
            console.error("Warning: Received unknown variable " + name);
        }

        console.error("Updated States Map: " + JSON.stringify(statesMap));
        console.error("Parent-Children Map: " + JSON.stringify(parentChildrenMap));
        console.error("Component Types Map: " + JSON.stringify(componentTypesMap));
    }
    
    /**
     * Generates the parent-children map and initializes the states map
     * based on the provided configuration strings.
     * 
     * @param configs The config string generated by the program.
     */
    function generateMaps(configs: string[]): void {
        parentChildrenMap = {};
        statesMap = {};
        componentTypesMap = {};
        for (let i = 0; i < configs.length; i++) {
            let parts = configs[i].split(",");
            if (parts.length == 0) continue;
            
            let type = parts[0];
            
            if (type == "B" || type == "TB") {
                // Button or ToggleButton: B,name or TB,name
                if (parts.length >= 2) {
                    let parentName = parts[1];
                    let childName = "value"; 
                    parentChildrenMap[parentName] = [childName];
                    statesMap[parentName + "." + childName] = "0";
                    componentTypesMap[parentName] = "Button";
                } else {
                    console.error("Setup failed for Button/ToggleButton!");
                }
            } else if (type == "S") {
                // Slider: S,min,max,name
                if (parts.length >= 4) {
                    let parentName = parts[3];
                    let childName = "value";
                    parentChildrenMap[parentName] = [childName];
                    statesMap[parentName + "." + childName] = "0";
                    componentTypesMap[parentName] = "Slider";
                } else {
                    console.error("Setup failed for Slider");
                }
            } else if (type == "TF") {
                // TextField: TF,name
                if (parts.length >= 2) {
                    let parentName = parts[1];
                    // unify all 1-attribute components to have a child called "value" for consistency
                    let childName = "value";
                    parentChildrenMap[parentName] = [childName];
                    statesMap[parentName + "." + childName] = "";
                    componentTypesMap[parentName] = "TextField";
                } else {
                    console.error("Setup failed for TextField");
                }
            } else if (type == "J") {
                // Joystick: J,anglename,smax,strengthName,joystickName
                if (parts.length >= 5) {
                    let angleName = parts[1];
                    // TO CONFIRM: is smax returned??
                    let strengthName = parts[3];
                    let joystickName = parts[4];
                    
                    // joystick has 2 attributes, angleName and strengthName
                    parentChildrenMap[joystickName] = [angleName, strengthName];
                    statesMap[joystickName + "." + angleName] = "0";
                    statesMap[joystickName + "." + strengthName] = "0";
                    componentTypesMap[joystickName] = "Joystick";
                } else {
                    console.error("Setup failed for Joystick");
                }
            } else if (type == "O") {
                // Variables List: O,count,name1,plot1,name2,plot2...
                // We treat each variable as its own parent with a single child "value"
                // Note: plotable is NOT changeable once initialized.
                if (parts.length >= 2) {
                    let count = parseInt(parts[1]);
                    for (let j = 0; j < count; j++) {
                        let nameIdx = 2 + (j * 2);
                        if (nameIdx < parts.length) {
                            let varName = parts[nameIdx];
                            parentChildrenMap[varName] = ["value"];
                            statesMap[varName + ".value"] = "0";
                            componentTypesMap[varName] = "Variable";
                        }
                    }
                } else {
                    console.error("Setup failed for Variables");
                }
            } else {
                console.error("Unknown config type: " + type);
            }
        }
        console.log("Parent-Children Map: " + JSON.stringify(parentChildrenMap));
        console.log("States Map: " + JSON.stringify(statesMap));
        console.log("Component Types Map: " + JSON.stringify(componentTypesMap));
    }

    /**
     * Enable Bluetooth and set up the remote GUI application framework.
     * You must use this before using all the other bluetooth blocks
     */
    //% blockId=pksdriver_bluetooth_setup block="setup bluetooth" subcategory="Bluetooth"
    //% group="Bluetooth"
    //% weight=99
    export function setupBluetooth(): void {

        bluetooth.startUartService();
        serial.setTxBufferSize(200);
        // DAL.MICROBIT_UART_S_DEFAULT_BUF_SIZE = 512;

        control.onEvent(DAL.MICROBIT_ID_BLE, DAL.MICROBIT_BLE_EVT_CONNECTED, function () {
            connected = true;
            basic.showLeds(`
                . . . . #
                . . . # .
                # . # . .
                . # . . .
                . . . . .
            `);
        });

        
        control.onEvent(DAL.MICROBIT_ID_BLE_UART, DAL.MICROBIT_UART_S_EVT_DELIM_MATCH, function () {
            
            // Read the data buffer up until the newline marker
            let receivedString = bluetooth.uartReadUntil(serial.delimiters(Delimiters.NewLine));
            console.log("got a message: " + receivedString);

            // Check if the message is a message from app
            if (receivedString && receivedString.indexOf("T,") === 0) {
                let parts = receivedString.split(",");
                
                // Ensure the string has at least the prefix and the parameter count
                if (parts.length >= 2) {
                    let numParams = parseInt(parts[1]);
                    
                    // Loop through each parameter pair
                    for (let i = 0; i < numParams; i++) {
                        // Calculate the array indices for the name and value
                        let nameIdx = 2 + (i * 2);
                        let valIdx = 3 + (i * 2);
                        
                        if (valIdx < parts.length) {
                            let pName = parts[nameIdx];
                            // .trim() removes any accidental trailing spaces or newline characters
                            let pValue = parts[valIdx].trim(); 
                            
                            // move shit out of this function so no more cluttering
                            updateMaps(pName, pValue);
                        }
                    }
                }
            }
        });

        control.onEvent(DAL.MICROBIT_ID_BLE, DAL.MICROBIT_BLE_EVT_DISCONNECTED, function () {
            connected = false;
        });

    }

    /**
     * Test function to test if sending data through bluetooth works.
     */
    //% blockId=pksdriver_bluetooth_setup_handlers block="setup bluetooth handlers" subcategory="Bluetooth"
    //% group="Bluetooth"
    //% weight=98
    export function initializeButtonHandlers(): void {
        
        // When pressing button A, send random values
        input.onButtonPressed(Button.A, () => {
            let v1 = Math.randomRange(0, 255);
            let v2 = Math.randomRange(0, 255);
            let v3 = Math.randomRange(0, 255);
            let v4 = Math.randomRange(0, 255);
            bluetooth.uartWriteLine("R,hello," + v1 + ",world," + v2 + ",ggez," + v3 + ",haha," + v4);
        });

        // When pressing button B, send fixed values
        input.onButtonPressed(Button.B, () => {
            bluetooth.uartWriteLine("R,hello,512,world,512,ggez,512,haha,512");
        });
    }

    /**
     * show the device name if it is not connected to bluetooth
     */
    //% blockId=pksdriver_bluetooth_showdname block="display micro:bit name" subcategory="Bluetooth"
    //% group="Bluetooth"
    //% weight=98
    export function showDeviceName(): void {
        // idk if this is actually needed but in case the children are so stupid that they don't know what
        // their device name is i made this function to show them what it is

        control.inBackground(() => {
            while (!connected) {
                basic.showString(control.deviceName())
                basic.pause(200)
            }
        })

    }

    /**
     * will tell you if microbit is connected to bluetooth or not
     */
    //% blockId=pksdriver_bluetooth_connected block="bluetooth is connected" subcategory="Bluetooth"
    //% group="Bluetooth"
    //% weight=98
    export function isConnected(): boolean {
        return connected;
    }

    /**
     * wait until you are connected to bluetooth
     * blocks next block
     */
    //% blockId=pksdriver_bluetooth_waitconn block="wait until bluetooth is connected" subcategory="Bluetooth"
    //% group="Bluetooth"
    //% weight=98
    export function waitUntilConnected(): void {
        while (!connected) {
            basic.pause(200)
        }
        console.log("done connected")
        // it actually takes like 1.4s for the connection to be stable 
        // so this exist to have a little buffer
        for (let i=0; i<10; i++) {
            console.log(`test send ${i}`)
            bluetooth.uartWriteLine("hi")
            basic.pause(200)
        }
    }

    /** =========================================
     *               CONFIGURATION
     *  =========================================
     *   This part deals with configuring the GUI on the app side. 
     *   Currently supports buttons, sliders, text fields, joysticks, and variables.
    **/ 


    /**
     * make configuration for GUI based on what you put in here.\n  
     * you must be connected to bluetooth!
     * @param configs The configuration list
     */
    // TODO: update subcategory in the future
    //% color="#f150f1"
    //% blockId=pksdriver_bluetooth_makeconfig block="make configuration with $configs" subcategory="Bluetooth"
    //% configs.shadow="lists_create_with"
    //% configs.defl="pksdriver_bluetooth_button"
    //% group="Configuration"
    //% weight=98
    export function makeConfiguration(configs: string[]): void {
        let config_string = `C,I,${configs.length},`
        if (configs.some(item => item.includes("O,"))) {
            config_string=`C,I,${configs.length-1},`
        }
        config_string += configs.join(",")
        config_string += "\n"

        // TODO: additional processing for plot is needed (i think)
        // PROCESSING GOES HERE...
        // generate the maps based on configs
        generateMaps(configs)

        if (!connected) {
            basic.showIcon(IconNames.No);
            return;
        }

        console.log(`send data: ${config_string}`)
        // automatically determine how long the configs are
        bluetooth.uartWriteLine(config_string)
    }

    /**
     * Creates a slider
     * @param min The minimum value of slider (>0), eg: 1
     * @param max The maximum value of slider (<=255), eg: 255
     * @param name The name of the slider
     */
    //% color="#f150f1"
    //% min.defl=0
    //% max.defl=255
    //% name.defl="Slider"
    //% blockId=pksdriver_bluetooth_slider block="create slider $min $max $name" subcategory="Bluetooth"
    //% group="Configuration"
    export function createSlider(min: number, max: number, name: string): string {

        // silently change min/max if they are set to the wrong value
        if (min > max) {
            const temp = min
            min = max
            max = temp
        }
        const output: string = `S,${min},${max},${name}`
        return output

    }

    /**
     * Creates a button
     * @param name The name of the button
     */
    //% color="#f150f1"
    //% name.defl="Button"
    //% blockId=pksdriver_bluetooth_button block="create button $name" subcategory="Bluetooth"
    //% group="Configuration"
    export function createButton(name: string): string {
        const output: string = `B,${name}`;
        return output;
    }

    /**
     * Creates a toggle button
     * @param name The name of the toggle button
     */
    //% color="#f150f1"
    //% name.defl="ToggleButton"
    //% blockId=pksdriver_bluetooth_toggle_button block="create toggle button $name" subcategory="Bluetooth"
    //% group="Configuration"
    export function createToggleButton(name: string): string {
        const output: string = `TB,${name}`;
        return output;
    }

    /**
     * Creates a text field
     * @param name The name of the text field
     */
    //% color="#f150f1"
    //% name.defl="TextField"
    //% blockId=pksdriver_bluetooth_textfield block="create text field $name" subcategory="Bluetooth"
    //% group="Configuration"
    export function createTextField(name: string): string {
        const output: string = `TF,${name}`;
        return output;
    }

    /**
     * Creates a joystick
     * @param anglename The name of the angle
     * @param smax The maximum value of the joystick
     * @param strengthName The name of the strength
     * @param joystickName The name of the joystick
     */
    //% color="#f150f1"
    //% anglename.defl="angle1"
    //% smax.min=0 smax.defl=255
    //% strengthName.defl="strength1"
    //% joystickName.defl="Joystick"
    //% blockId=pksdriver_bluetooth_joystick block="create joystick $joystickName angle $anglename max strength $smax strength $strengthName" subcategory="Bluetooth"
    //% group="Configuration"
    export function createJoystick(anglename: string, smax: number, strengthName: string, joystickName: string): string {
        const output: string = `J,${anglename},${smax},${strengthName},${joystickName}`;
        return output;
    }

    /**
     * Creates a single variable configuration.
     * @param name The name of the variable
     * @param isPlotable Whether the variable is plotable
     */
    //% color="#a000a0"
    //% name.defl="var1"
    //% blockId=pksdriver_bluetooth_var block="variable $name plotable $isPlotable" subcategory="Bluetooth"
    //% group="Configuration"
    export function createVariable(name: string, isPlotable: boolean): string {
        // Returns a formatted string for this single variable
        return `${name},${isPlotable}`;
    }

    /**
     * A list of variables. You must wrap this around your variables, else they will not work.
     * @param vars The list of variable strings
     */
    //% color="#f150f1"
    //% blockId=pksdriver_bluetooth_varlist block="variables $vars" subcategory="Bluetooth"
    //% group="Configuration"
    //% vars.shadow="lists_create_with"
    //% vars.defl="pksdriver_bluetooth_var"
    export function formatVariablesList(vars: string[]): string {
        // Start with the prefix and the length of the list
        let output: string = `O,${vars.length}`;
        
        // Append each variable string from the list
        for (let i = 0; i < vars.length; i++) {
            output += `,${vars[i]}`;
        }
        
        return output;
    }

    /**
     * =========================================
     *                GETTERS
     * =========================================
     * For allowing the user to do stuff with the
     * data that is sent from the app to the microbit
     */

}

/*
DEBUGGING PURPOSES ONLY
original code:

function initializeBluetooth() {

    // set up the bluetooth config that 

    bluetooth.startUartService()

    bluetooth.onBluetoothConnected(function () {
        basic.showLeds(`
        . . . . #
        . . . # .
        # . # . .
        . # . . .
        . . . . .
        `)
        loops.everyInterval(500, function on_every_interval() {
            // this is the config data that should be sent to the app 
            // to set up the GUI 
            bluetooth.uartWriteLine("C,I,12,B,button1,B,button2,B,button3,B,button4,B,button5,B,button6,B,button7,S,0,255,slider1,S,0,255,slider2,S,0,255,slider3,TB,toggleButton1,TB,toggleButton2,O,3,hello,true,world,true,ggez,true,haha,false")
        })
    })
}

function intializeButtonHandlers() {
    // what this does is that when u press button A, it will send the line below
    input.onButtonPressed(Button.A, () => {
        bluetooth.uartWriteLine("R,hello," + randint(0, 255) + ",world," + randint(0, 255) + ",ggez," + randint(0, 255) + ",haha," + randint(0, 255))
    })

    // same as above but with button B, all values are set to 512
    input.onButtonPressed(Button.B, () => {
        bluetooth.uartWriteLine("R,hello," + 512 + ",world," + 512 + ",ggez," + 512 + ",haha," + 512)
    })

}

initializeBluetooth()
intializeButtonHandlers()
*/